# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
org.gradle.jvmargs=-Xms1024M -Xmx4096M -Dfile.encoding=UTF-8 -Didea.kotlin.plugin.use.k2=true --add-opens java.base/java.lang=ALL-UNNAMED -Dkotlin.daemon.jvm.options="-Dfile.encoding=UTF-8,-Didea.kotlin.plugin.use.k2=true" 
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# Build optimization
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=false
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.max-problems=5
org.gradle.configureondemand=false

# Kotlin optimization
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.caching.enabled=false
kotlin.code.style=official

android.enableJetifier=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.r8.strictFullModeForKeepRules=false


# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
